version: v1.0
name: App build release

agent:
  machine:
    type: e1-standard-2
  containers:
    - name: main
      image: 'registry.semaphoreci.com/rust:1.51'

blocks:
  - name: Release
    task:
      secrets:
        - name: production-release
      jobs:
      - name: Push code
        commands:
          - sem-version node 16.13.0
          - checkout
          - yarn install
          - yarn generate-types
          - yarn tauri build
          - node ./scripts/production-release.js
