version: v1.0
name: App build release

agent:
  machine:
    type: e1-standard-2
  containers:
    - name: main
      image: 'registry.semaphoreci.com/rust:1.51-node'

blocks:
  - name: Release
    task:
      secrets:
        - name: production-release
      jobs:
      - name: Push code
        commands:
          # download and install nvm
          - wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          - ~/.nvm install 16.13.0
          - ~/.nvm use 16.13.0
          - node -v
          # - npm install --global yarn
          # - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          # - source ~/.bash_profile
          # - checkout
          # - yarn install
          # - yarn generate-types
          # - yarn tauri build
          # - node ./scripts/production-release.js
